#!/bin/bash
set -e

filesToFormat="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $2 ~ /\.nb/ { print $2}')"

wolframscript Scripts/FormatNotebooks.wls "$filesToFormat"

for sourceFilePath in $filesToFormat
do
  git add $sourceFilePath
done;
