name: Check
on: 
  schedule:
    - cron: '30 12 * * *'
  pull_request: 
    branches:  [main]
  workflow_dispatch:
jobs: 
  Check: 
    name: Check
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:latest
      options: --user root
    env: 
      WOLFRAM_SYSTEM_ID: Linux-x86-64
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
      RESOURCE_PUBLISHER_TOKEN: ${{ secrets.RESOURCE_PUBLISHER_TOKEN }}
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v2
    - name: Build paclet MX
      run: wolframscript Scripts/BuildMX.wls
    - name: Check
      id: check-paclet-step
      uses: rhennigan/check-paclet@v1.7.1
      with: 
        target: Submit
        paclet_cicd_version: 0.26.0
        definition_notebook: ./ResourceDefinition.nb
        resource_system_base: https://www.wolframcloud.com/obj/resourcesystem/api/1.0
  Test: 
    name: Test
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:latest
      options: --user root
    env: 
      WOLFRAM_SYSTEM_ID: Linux-x86-64
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
      RESOURCE_PUBLISHER_TOKEN: ${{ secrets.RESOURCE_PUBLISHER_TOKEN }}
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v2
    - name: Build paclet MX
      run: wolframscript Scripts/BuildMX.wls
    - name: Test
      id: test-paclet-step
      uses: rhennigan/test-paclet@v1.7.1
      with: 
        target: Submit
        paclet_cicd_version: 0.26.0
        definition_notebook: ./ResourceDefinition.nb
        resource_system_base: https://www.wolframcloud.com/obj/resourcesystem/api/1.0
    - name: UploadArtifact
      id: upload-build-artifacts-step
      uses: actions/upload-artifact@v2
      with: 
        path: ${{ env.PACLET_TEST_RESULTS }}
        if-no-files-found: ignore