name: Check
on: 
  push: 
    branches:  [feature/paclet-cicd-updates]
  pull_request: 
    branches:  [main]
  workflow_dispatch:

env: 
  WOLFRAM_SYSTEM_ID:           Linux-x86-64
  WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
  RESOURCE_PUBLISHER_TOKEN:    ${{ secrets.RESOURCE_PUBLISHER_TOKEN }}

jobs: 
  Check: 
    name: Check
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:latest
      options: --user root
    
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v2
    - name: Check
      id: check-paclet-step
      uses: rhennigan/check-paclet@v1.7.1
      with: 
        target: Submit
        paclet_cicd_version: 0.17.1
        definition_notebook: ./ResourceDefinition.nb
        resource_system_base: https://www.wolframcloud.com/obj/rhennigan/api/1.0
  
  Submit:
    name: Submit
    needs: [Check]
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:latest
      options: --user root

    timeout-minutes: 20
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Check
        id: submit-paclet-step
        uses: rhennigan/submit-paclet@v1.7.1
        with: 
          paclet_cicd_version: 0.17.1
          definition_notebook: ./ResourceDefinition.nb
          resource_system_base: https://www.wolframcloud.com/obj/rhennigan/api/1.0