name: Check
on: 
  workflow_dispatch:
  pull_request: 
    branches:  [main]
  schedule: 
  - cron: '30 12 * * *'
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true
env: 
  RESOURCE_PUBLISHER_TOKEN: ${{ secrets.RESOURCE_PUBLISHER_TOKEN }}
  WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
  WLPR_PACLET_SITE: https://resources.wolframcloud.com/PacletRepository/pacletsite
jobs: 
  Check: 
    name: Check
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:13.0.1
      options: --user root
    env: 
      WOLFRAM_SYSTEM_ID: Linux-x86-64
    timeout-minutes: 15
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v3
    - name: BuildMX
      run: |
        if [ "${{ env.WLPR_PACLET_SITE }}" != "" ]
        then
            echo 'Updating paclet sites...'
            wolframscript -code 'PacletInstall["PacletManager"];PacletSiteRegister["${{ env.WLPR_PACLET_SITE }}"];PacletSiteUpdate[PacletSites[]];Quit[]' > /dev/null
        fi
        wolframscript Scripts/BuildMX.wls
    - name: Build
      id: build-paclet-step
      uses: WolframResearch/build-paclet@v1.10.2
      with: 
        target: Submit
        paclet_cicd_version: 0.33.3
        definition_notebook: ./ResourceDefinition.nb
        resource_system_base: https://www.wolframcloud.com/obj/resourcesystem/api/1.0
    - name: UploadArtifact
      id: upload-build-artifacts-step
      uses: actions/upload-artifact@v3
      with: 
        path: ${{ env.PACLET_BUILD_DIR }}
        if-no-files-found: ignore
  Test: 
    name: Test
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:13.0.1
      options: --user root
    env: 
      WOLFRAM_SYSTEM_ID: Linux-x86-64
    timeout-minutes: 30
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v3
    - name: BuildMX
      run: |
        if [ "${{ env.WLPR_PACLET_SITE }}" != "" ]
        then
            echo 'Updating paclet sites...'
            wolframscript -code 'PacletInstall["PacletManager"];PacletSiteRegister["${{ env.WLPR_PACLET_SITE }}"];PacletSiteUpdate[PacletSites[]];Quit[]' > /dev/null
        fi
        wolframscript Scripts/BuildMX.wls
    - name: Test
      id: test-paclet-step
      uses: WolframResearch/test-paclet@v1.10.2
      with: 
        target: Submit
        paclet_cicd_version: 0.33.3
        definition_notebook: ./ResourceDefinition.nb
        resource_system_base: https://www.wolframcloud.com/obj/resourcesystem/api/1.0