name: Check
on: 
  pull_request: 
    branches:  [main]
  workflow_dispatch:
  schedule: 
  - cron: '30 12 * * *'
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true
env: 
  WOLFRAM_SYSTEM_ID: Linux-x86-64
  WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
  RESOURCE_PUBLISHER_TOKEN: ${{ secrets.RESOURCE_PUBLISHER_TOKEN }}
jobs: 
  Check: 
    name: Check
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:latest
      options: --user root
    timeout-minutes: 15
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v3
    - name: BuildMX
      run: wolframscript Scripts/BuildMX.wls
    - name: Build
      id: build-paclet-step
      uses: WolframResearch/build-paclet@v1.9.0
      with: 
        target: Submit
        paclet_cicd_version: 0.32.0
        definition_notebook: ./ResourceDefinition.nb
        resource_system_base: https://www.wolframcloud.com/obj/resourcesystem/api/1.0
    - name: UploadArtifact
      id: upload-build-artifacts-step
      uses: actions/upload-artifact@v3
      with: 
        path: ${{ env.PACLET_BUILD_DIR }}
        if-no-files-found: ignore
  Test: 
    name: Test
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:latest
      options: --user root
    timeout-minutes: 30
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v3
    - name: BuildMX
      run: wolframscript Scripts/BuildMX.wls
    - name: Test
      id: test-paclet-step
      uses: WolframResearch/test-paclet@v1.9.0
      with: 
        target: Submit
        paclet_cicd_version: 0.32.0
        definition_notebook: ./ResourceDefinition.nb
        resource_system_base: https://www.wolframcloud.com/obj/resourcesystem/api/1.0
    - name: UploadTestResults
      id: upload-test-results-step
      if: always() && env.PACLET_TEST_RESULTS
      uses: actions/upload-artifact@v3
      with: 
        path: ${{ env.PACLET_TEST_RESULTS }}
        if-no-files-found: ignore