name: Build Paclet

# Controls when the workflow will run
on:
  push:
    # Triggers the workflow on push for the following branches
    branches: [ main ]
  pull_request:
    # Triggers the workflow on pull request for the following branches
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  CheckAndBuild:
    name: Check and Build

    # Choose which type of machine to run the job on
    runs-on: ubuntu-latest

    # Choose the docker container
    container:
      # https://hub.docker.com/r/wolframresearch/wolframengine
      image: wolframresearch/wolframengine:latest
      options: --user root

    # Environment variables
    env:
      WOLFRAM_SYSTEM_ID: Linux-x86-64

      # Set WOLFRAMSCRIPT_ENTITLEMENTID environment variable
      #   created with CreateLicenseEntitlement (https://reference.wolfram.com/language/ref/CreateLicenseEntitlement.html)
      #   stored in GitHub repository settings as an encrypted secret (https://docs.github.com/en/actions/security-guides/encrypted-secrets)
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAM_LICENSE_ENTITLEMENT_ID }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v2

      - name: Build Paclet
        uses: rhennigan/build-paclet@main
        with:
          check: false
          debug: true
      
      - name: Check files
        run: | 
          echo $GITHUB_WORKSPACE
          ls -a $GITHUB_WORKSPACE
          echo $BUILD_DIR

      - name: Upload build artifacts
        if: success() || failure()    # run this step even if previous step failed
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.GITHUB_WORKSPACE }}/build
          if-no-files-found: error

  # Currently disabled since this takes much longer to run
  TestReport:
    if: ${{ false }}  # disable for now
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:latest
      options: --user root
    env:
      WOLFRAM_SYSTEM_ID: Linux-x86-64

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run all tests
        env:
          WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAM_LICENSE_ENTITLEMENT_ID }}
        run: wolframscript Scripts/TestReport.wls

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-results/**/*.xml

      - name: Upload test artifacts
        if: success() || failure()    # run this step even if previous step failed
        uses: actions/upload-artifact@v2
        with:
          name: test-artifacts
          path: test-results/
          if-no-files-found: error