name: PacletBuild
on: 
  push: 
    branches:  [feature/paclet-cicd-updates]
jobs: 
  Check: 
    name: Check
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:latest
      options: --user root
    env: 
      WOLFRAM_SYSTEM_ID: Linux-x86-64
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
    timeout-minutes: 10
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v2
    - name: Check
      id: check-paclet-step
      uses: rhennigan/check-paclet@v1.4.0
      with: 
        target: Submit
        paclet_cicd_version: 0.7.0
        definition_notebook: ./DefinitionNotebook.nb
  TestReport: 
    name: TestReport
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:latest
      options: --user root
    env: 
      WOLFRAM_SYSTEM_ID: Linux-x86-64
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v2
    - name: TestReport
      run: wolframscript Scripts/TestReport.wls
  Build: 
    needs:  [Check, TestReport]
    name: Build
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:latest
      options: --user root
    env: 
      WOLFRAM_SYSTEM_ID: Linux-x86-64
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
    timeout-minutes: 10
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v2
    - name: Build
      id: build-paclet-step
      uses: rhennigan/build-paclet@v1.4.0
      with: 
        target: Submit
        paclet_cicd_version: 0.7.0
        definition_notebook: ./DefinitionNotebook.nb
    - name: UploadArtifact
      id: upload-build-artifacts-step
      uses: actions/upload-artifact@v2
      with: 
        path: ${{ env.BUILD_DIR }}
        if-no-files-found: error