name: Submit
on: 
  push: 
    branches:  [release/*]
  workflow_dispatch:
jobs: 
  Submit: 
    name: Submit
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:latest
      options: --user root
    env: 
      WOLFRAM_SYSTEM_ID: Linux-x86-64
      WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
      RESOURCE_PUBLISHER_TOKEN: ${{ secrets.RESOURCE_PUBLISHER_TOKEN }}
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v2
    - name: Build paclet MX
      run: wolframscript Scripts/BuildMX.wls
    - name: Submit
      id: submit-paclet-step
      uses: rhennigan/submit-paclet@v1.7.1
      with: 
        paclet_cicd_version: 0.26.0
        definition_notebook: ./ResourceDefinition.nb
        resource_system_base: https://www.wolframcloud.com/obj/resourcesystem/api/1.0
    - name: UploadArtifact
      id: upload-build-artifacts-step
      uses: actions/upload-artifact@v2
      with: 
        path: ${{ env.PACLET_BUILD_DIR }}
        if-no-files-found: ignore